# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Insured's Name")),
                ('underwriter', models.CharField(blank=True, max_length=30, null=True, verbose_name="Underwriter's name")),
                ('date', models.DateField(auto_now=True)),
                ('rating_state', localflavor.us.models.USStateField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('M', 'Mercantile'), ('G', 'Governmental')], max_length=1)),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mod_factor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('class_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sfaa_fidelity_loss_cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('company_loss_cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_employees', models.PositiveIntegerField()),
                ('insurance_limit', models.PositiveIntegerField()),
                ('exposure_points', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='InsuringAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='limit')),
                ('deductible', models.PositiveIntegerField(default=0)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Premium')),
                ('agreement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.AgreementType')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('account_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='djangoinsurancerater.AccountInfo')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.ClassCode')),
            ],
        ),
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField()),
                ('rateable_count', models.PositiveIntegerField()),
                ('locations', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='risk_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.RiskData'),
        ),
        migrations.AddField(
            model_name='insuringagreement',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='djangoinsurancerater.Quote'),
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together=set([('number_employees', 'insurance_limit')]),
        ),
    ]
