# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('rating_state', localflavor.us.models.USStateField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('M', 'Mercantile'), ('G', 'Governmental')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mod_factor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('class_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sfaa_fidelity_loss_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('company_loss_cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_employees', models.PositiveIntegerField()),
                ('insurance_limit', models.PositiveIntegerField()),
                ('exposure_points', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='InsuringAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_limit', models.PositiveIntegerField()),
                ('deductible', models.PositiveIntegerField()),
                ('agreement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.AgreementType')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underwriter', models.CharField(max_length=30)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('account_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.AccountInfo')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.ClassCode')),
                ('insuring_agreements', models.ManyToManyField(to='djangoinsurancerater.InsuringAgreement')),
            ],
        ),
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField()),
                ('rateable_count', models.PositiveIntegerField()),
                ('locations', models.PositiveIntegerField()),
            ],
        ), 
        migrations.AddField(
            model_name='quote',
            name='risk_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.RiskData'),
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together=set([('number_employees', 'insurance_limit')]),
        ),
    ]
