# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinsurancerater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='insuring_agreements',
        ),
        migrations.AddField(
            model_name='insuringagreement',
            name='quote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='djangoinsurancerater.Quote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classcode',
            name='company_loss_cost',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='classcode',
            name='sfaa_fidelity_loss_cost',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
