# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinsurancerater', '0003_auto_20160825_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='underwriter',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='underwriter',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Underwriter's name"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='account_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='djangoinsurancerater.AccountInfo'),
        ),
    ]
