# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinsurancerater', '0004_auto_20160829_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuringagreement',
            name='agreement_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='djangoinsurancerater.AgreementType'),
        ),
        migrations.AlterField(
            model_name='insuringagreement',
            name='deductible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuringagreement',
            name='insurance_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuringagreement',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Premium'),
        ),
    ]
