# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinsurancerater', '0008_auto_20160901_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcode',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='insuringagreement',
            name='insurance_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limit'),
        ),
    ]
