# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinsurancerater', '0010_auto_20160918_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementtype',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insuringagreement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
